// ====
// THIS NEEDS TO BE AUTOGENERATED FROM datamodel.prisma & uses
// './generated/prisma-client'
// ====

import { Context } from './utils'

const Resolvers = {
    Query: {
      balances(parent, args, context: Context) {
        return context.prisma.balances()
      },
    }
  }

export default Resolvers