import { GraphQLServer, Options } from 'graphql-yoga'
import { prisma, BalanceWhereInput } from './generated/prisma-client'
import { Context } from './utils'

// ====
// THIS NEEDS TO BE AUTOGENERATED FROM datamodel.prisma & uses
// './generated/prisma-client'
// ====

const resolvers = {
  Query: {
    balances(parent, args, context: Context) {
      return context.prisma.balances()
    },
  }
}

const server = new GraphQLServer({
  typeDefs: './src/schema.graphql',
  resolvers,
  context: { prisma },
})

const server_options = {
  port: 400
} as Options;

server.start(server_options,() => console.log(`Server is running on http://localhost:${server_options.port}`))

